"""create talks table

Revision ID: 17a34b8c161a
Revises: 
Create Date: 2026-08-13 01:32:08.927365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '17a34b8c161a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('speaker', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talks')
    # ### end Alembic commands ###
